"use client";
import {useEffect,useState} from "react";
import {CalendarDays,Check,CircleDollarSign,Flame,LogOut,MapPin,MessageCircle,Plus,Settings2,TentTree,Trash2,Users,Vote} from "lucide-react";
import {createBrowserClient} from "@supabase/ssr";
import {Button} from "@/components/ui/button"; import {Input} from "@/components/ui/input"; import {Tabs,TabsContent,TabsList,TabsTrigger} from "@/components/ui/tabs"; import {Textarea} from "@/components/ui/textarea";
type Person={name:string;going:boolean}; type S={trip:{name:string;startDate:string;endDate:string;place:string;region:string;note:string};people:Person[];poll:{label:string;voters:string[]}[];gear:{id:number;item:string;owner:string|null}[];messages:{id:number;name:string;body:string}[];expenses:{id:number;item:string;paidBy:string;amount:number}[]};
const seed:S={trip:{name:"A weekend under the gum trees",startDate:"2026-10-16",endDate:"2026-10-18",place:"Bents Basin",region:"NSW",note:"Blue Mountains weekend"},people:[{name:"Ikhwam",going:true},{name:"Najwa",going:true},{name:"Nani",going:false},{name:"Hakim",going:true}],poll:[{label:"Bents Basin · 16–18 Oct",voters:["Ikhwam","Najwa","Hakim"]},{label:"Cattai · 23–25 Oct",voters:["Najwa","Nani"]},{label:"The Basin · 6–8 Nov",voters:["Hakim"]}],gear:[{id:1,item:"6-person tent",owner:"Ikhwam"},{id:2,item:"Camping stove + gas",owner:"Najwa"},{id:3,item:"First-aid kit",owner:null},{id:4,item:"Firewood",owner:"Hakim"},{id:5,item:"Ice box",owner:null}],messages:[{id:1,name:"Najwa",body:"Bents Basin looks best for the kids. It has toilets and it’s not too far from Sydney."},{id:2,name:"Hakim",body:"I can bring firewood and folding chairs. Should we do a BBQ on Saturday night?"},{id:3,name:"Nani",body:"I’m checking my roster tomorrow — keep me as maybe for now 😊"}],expenses:[{id:1,item:"Campsite booking",paidBy:"Ikhwam",amount:168},{id:2,item:"BBQ groceries",paidBy:"Najwa",amount:86.4}]};
const ini=(n:string)=>n.slice(0,2).toUpperCase(); const prettyDates=(a:string,b:string)=>{if(!a)return"Dates not set";const f=(v:string,o:Intl.DateTimeFormatOptions)=>new Date(v+"T12:00:00").toLocaleDateString("en-AU",o);if(!b||a===b)return f(a,{day:"numeric",month:"long",year:"numeric"});return `${f(a,{day:"numeric"})}–${f(b,{day:"numeric",month:"long",year:"numeric"})}`};
export default function Home(){
 const[data,setData]=useState(seed),[name,setName]=useState(""),[email,setEmail]=useState(""),[authReady,setAuthReady]=useState(false),[draft,setDraft]=useState(""),[item,setItem]=useState(""),[newPerson,setNewPerson]=useState(""),[cost,setCost]=useState({item:"",amount:""}),[saving,setSaving]=useState(false);
 useEffect(()=>{const supabase=createBrowserClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);supabase.auth.getUser().then(({data:{user}})=>{if(!user){location.href="/login";return}setName(user.user_metadata?.full_name||user.email?.split("@")[0]||"Camper");setEmail(user.email||"");setAuthReady(true);fetch("/api/camp").then(r=>r.json()).then(v=>{if(v.data)setData({...v.data,trip:v.data.trip||seed.trip})}).catch(()=>{})})},[]);
 useEffect(()=>{const d=document as Document&{modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>void|Promise<void>}};if(!d.modelContext?.registerTool)return;const a=new AbortController();void Promise.resolve(d.modelContext.registerTool({name:"add_discussion_message",title:"Post camping message",description:"Post a message to the camping-plan discussion as the selected member.",inputSchema:{type:"object",properties:{message:{type:"string",minLength:1,maxLength:500}},required:["message"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(input:unknown)=>{const message=(input as {message?:string}).message?.trim();if(!message)throw new Error("Message is required");const next={...data,messages:[...data.messages,{id:Date.now(),name,body:message}]};await save(next);return{posted:true,member:name,message}}},{signal:a.signal})).catch(()=>{});return()=>a.abort()},[data,name]);
 async function save(n:S){setData(n);setSaving(true);try{await fetch("/api/camp",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({data:n})})}finally{setSaving(false)}}
 const going=data.people.filter(p=>p.going).length,total=data.expenses.reduce((s,e)=>s+e.amount,0),lead=Math.max(1,...data.poll.map(p=>p.voters.length)); const trip=(key:keyof S["trip"],value:string)=>save({...data,trip:{...data.trip,[key]:value}});
 const addPerson=()=>{const n=newPerson.trim();if(!n||data.people.some(p=>p.name.toLowerCase()===n.toLowerCase()))return;save({...data,people:[...data.people,{name:n,going:true}]});setNewPerson("")}; const removePerson=(person:string)=>{if(data.people.length===1)return;const people=data.people.filter(p=>p.name!==person);save({...data,people,poll:data.poll.map(p=>({...p,voters:p.voters.filter(v=>v!==person)})),gear:data.gear.map(g=>g.owner===person?{...g,owner:null}:g)});if(name===person)setName(people[0].name)};
 if(!authReady)return <main className="auth-loading"><Flame/><b>Opening Campfire Circle…</b></main>;
 return <main className="min-h-screen pb-20"><header><div className="top"><div className="brand"><span className="logo"><Flame/></span><div><b>Campfire Circle</b><small>{data.trip.note||"Your group camping plan"}</small></div></div><div className="who"><span>{saving?"Saving…":email}</span><b>{name}</b><button aria-label="Sign out" onClick={async()=>{const s=createBrowserClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);await s.auth.signOut();location.href="/login"}}><LogOut/></button></div></div></header>
 <section className="hero"><div className="hero-in"><div><em>TRIP 01 · YOUR PLAN</em><h1>{data.trip.name||"Untitled camping trip"}</h1><div className="facts"><span><CalendarDays/>{prettyDates(data.trip.startDate,data.trip.endDate)}</span><span><MapPin/>{[data.trip.place,data.trip.region].filter(Boolean).join(", ")||"Place not set"}</span><span><Users/>{going} going</span></div></div><div className="faces">{data.people.map((p,i)=><i key={p.name} className={p.going?"":"maybe"} style={{background:["#e99052","#68a48f","#e4b75f","#668bb0"][i%4]}}>{ini(p.name)}</i>)}</div></div></section>
 <div className="wrap"><div className="stats"><Stat v={going+"/"+data.people.length} l="Confirmed"/><Stat v={String(data.gear.filter(g=>!g.owner).length)} l="Items open"/><Stat v={going?"$"+(total/going).toFixed(0):"$0"} l="Each so far"/></div>
 <Tabs defaultValue="details"><TabsList className="tabs"><TabsTrigger value="details"><Settings2/>Details</TabsTrigger><TabsTrigger value="chat"><MessageCircle/>Discuss</TabsTrigger><TabsTrigger value="vote"><Vote/>Vote</TabsTrigger><TabsTrigger value="pack"><TentTree/>Pack</TabsTrigger><TabsTrigger value="cost"><CircleDollarSign/>Costs</TabsTrigger></TabsList>
 <TabsContent value="details"><div className="details-grid"><section className="card pad"><Title k="TRIP DETAILS" t="Set up your weekend"/><div className="form-grid"><label className="wide">Trip name<Input value={data.trip.name} onChange={e=>trip("name",e.target.value)} placeholder="Weekend under the stars"/></label><label>Start date<Input type="date" value={data.trip.startDate} onChange={e=>trip("startDate",e.target.value)}/></label><label>End date<Input type="date" min={data.trip.startDate} value={data.trip.endDate} onChange={e=>trip("endDate",e.target.value)}/></label><label>Place<Input value={data.trip.place} onChange={e=>trip("place",e.target.value)} placeholder="Campsite or park"/></label><label>State / region<Input value={data.trip.region} onChange={e=>trip("region",e.target.value)} placeholder="NSW"/></label><label className="wide">Short note<Input value={data.trip.note} onChange={e=>trip("note",e.target.value)} placeholder="Family camping weekend"/></label></div><p className="save-note">Changes save automatically for everyone.</p></section>
 <section className="card people-card"><Title k="PEOPLE" t={`${data.people.length} invited`}/><div className="add"><Input value={newPerson} onChange={e=>setNewPerson(e.target.value)} onKeyDown={e=>e.key==="Enter"&&addPerson()} placeholder="Add a person"/><Button onClick={addPerson}><Plus/> Add</Button></div>{data.people.map(p=><div className="person" key={p.name}><i>{ini(p.name)}</i><b>{p.name}</b><button className={p.going?"going":"maybe-status"} onClick={()=>save({...data,people:data.people.map(x=>x.name===p.name?{...x,going:!x.going}:x)})}>{p.going?"Going":"Maybe"}</button><button className="remove" aria-label={`Remove ${p.name}`} onClick={()=>removePerson(p.name)} disabled={data.people.length===1}><Trash2/></button></div>)}</section></div></TabsContent>
 <TabsContent value="chat"><section className="card"><Title k="GROUP CHAT" t="Sort out the details"/><div className="chat">{data.messages.map(m=><div key={m.id} className={"msg "+(m.name===name?"mine":"")}><i>{ini(m.name)}</i><div><b>{m.name}</b><p>{m.body}</p></div></div>)}</div><div className="compose"><Textarea value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Share an idea or ask the group…"/><Button onClick={()=>{if(draft.trim()){save({...data,messages:[...data.messages,{id:Date.now(),name,body:draft.trim()}]});setDraft("")}}}>Send</Button></div></section></TabsContent>
 <TabsContent value="vote"><section className="card pad"><Title k="CAMPSITE + DATE" t="Which option works best?"/><div className="options">{data.poll.map((p,i)=>{const picked=p.voters.includes(name);return <button key={p.label} className={picked?"picked":""} onClick={()=>save({...data,poll:data.poll.map((x,j)=>j===i?{...x,voters:picked?x.voters.filter(v=>v!==name):[...x.voters,name]}:x)})}><i>{picked?<Check/>:i+1}</i><span><b>{p.label}</b><small>{p.voters.join(", ")}</small><em style={{width:(p.voters.length/lead*100)+"%"}}/></span><strong>{p.voters.length}</strong></button>})}</div></section></TabsContent>
 <TabsContent value="pack"><section className="card"><Title k="SHARED CHECKLIST" t="Who’s bringing what?"/><div className="add"><Input value={item} onChange={e=>setItem(e.target.value)} placeholder="Add shared item"/><Button onClick={()=>{if(item.trim()){save({...data,gear:[...data.gear,{id:Date.now(),item:item.trim(),owner:null}]});setItem("")}}}>Add</Button></div>{data.gear.map(g=><div className="gear" key={g.id}><button onClick={()=>save({...data,gear:data.gear.map(x=>x.id===g.id?{...x,owner:x.owner?null:name}:x)})}>{g.owner&&<Check/>}</button><b>{g.item}</b><span>{g.owner||"Needs owner"}</span></div>)}</section></TabsContent>
 <TabsContent value="cost"><div className="cost-grid"><section className="card"><Title k="TRIP KITTY" t="Shared costs"/>{data.expenses.map(e=><div className="expense" key={e.id}><i>{ini(e.paidBy)}</i><span><b>{e.item}</b><small>Paid by {e.paidBy}</small></span><strong>${e.amount.toFixed(2)}</strong></div>)}</section><aside className="card pad"><Title k="ADD EXPENSE" t={"$"+total.toFixed(2)+" total"}/><Input value={cost.item} onChange={e=>setCost({...cost,item:e.target.value})} placeholder="What was it for?"/><Input value={cost.amount} onChange={e=>setCost({...cost,amount:e.target.value})} placeholder="Amount ($)"/><Button className="w-full" onClick={()=>{const a=Number(cost.amount);if(cost.item.trim()&&a){save({...data,expenses:[...data.expenses,{id:Date.now(),item:cost.item,paidBy:name,amount:a}]});setCost({item:"",amount:""})}}}>Add expense</Button></aside></div></TabsContent></Tabs></div></main>}
function Stat({v,l}:{v:string;l:string}){return <div className="stat"><b>{v}</b><small>{l}</small></div>} function Title({k,t}:{k:string;t:string}){return <div className="title"><em>{k}</em><h2>{t}</h2></div>}
